# Generated by Django 6.0.2 on 2026-03-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ноутбук ACER', max_length=100)),
                ('description', models.TextField(default='игровой ноутбук.......')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('serial_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tovars.product')),
            ],
        ),
    ]
