# Generated by Django 6.0.2 on 2026-03-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovars', '0002_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='прикольный ноутбук')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('choice_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tovars.product')),
            ],
        ),
    ]
