# Generated by Django 6.0.2 on 2026-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=50, verbose_name='укажите название книги')),
                ('description', models.TextField(verbose_name='укажите описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите обложку')),
                ('category_book', models.CharField(choices=[('фантастика', 'фантастика'), ('хоррор', 'хоррор'), ('исторические', 'исторические')], max_length=100, verbose_name='выберите категорию')),
                ('url_audio_book', models.URLField(verbose_name='укажите ссылку на аудиокнигу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
