# Generated by Django 6.0.2 on 2026-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
